service: rmanalyzer

# frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12
  iam:
    role:
      managedPolicies:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
        - "arn:aws:iam::aws:policy/AmazonSESFullAccess"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  stage: prd
  region: us-east-1

package:
 patterns:
   - main.py

plugins:
  - serverless-python-requirements

functions:
  process_transactions:
    handler: main.lambda_handler
    events:
      - s3:
          bucket: rm-analyzer-sheets-prd
          event: s3:ObjectCreated:Put
          existing: true

resources:
  Resources:
    S3Invoke:
      Type: "AWS::Lambda::Permission"
      Properties:
        Action: "lambda:InvokeFunction"
        FunctionName:
          Fn::GetAtt: [ProcessUnderscoretransactionsLambdaFunction, Arn]
        Principal: "s3.amazonaws.com"
        SourceAccount: "790151521070"
        SourceArn: "arn:aws:s3:::rm-analyzer-sheets-prd"
