on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: Assert Types
        run: |
          OUTPUT=$(mypy ./lambda_function/src/main.py)
          if [ -n "$(echo $OUTPUT | grep 'Success')" ]; then
            echo "mypy type check passed"
          else
            echo "mypy type check failed"
            exit 1
          fi

      - name: Run tests
        run: python -m unittest discover
  
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # - name: Install Python dependencies
      #   run: pip install -r requirements.txt
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm install -g serverless

      - name: Install serverless-python-requirements
        run: serverless plugin install -n serverless-python-requirements

      - name: Deploy to AWS Lambda
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
